//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayerDXMonoGamePort {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class RequestedSong : global::System.Configuration.ApplicationSettingsBase {
        
        private static RequestedSong defaultInstance = ((RequestedSong)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RequestedSong())));
        
        public static RequestedSong Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RequestedSongString {
            get {
                return ((string)(this["RequestedSongString"]));
            }
            set {
                this["RequestedSongString"] = value;
            }
        }
    }
}
